== Centipede for CloudReady
A modified version of https://create.arduino.cc/editor/Amplified_Labs/779bb0d9-aa40-4245-b4e9-988adc6d19df/preview[Amplified Lab's script] for enrolling CloudReady devices into managed environments.

Disclaimer: Not all versions of CloudReady work with this script. Check out out the https://github.com/neverware/AmplifiedIT-Centipede/tags[Tags] page to select the version of the script that is closest to your version of CloudReady. We do not update this script for every version of CloudReady, so you may need to make modifications if your version is not listed. 

== 1: Configuration
Change the settings in the top section of the sketch file. Make sure to have the correct ones selected, or else the script won't execute correctly.

== 2: Load the code
Load the code onto an arduino that works with the https://www.arduino.cc/reference/en/language/functions/usb/keyboard/[Keyboard library]. The https://labs.amplifiedit.com/centipede/[Centipede Help Page] recommends using the https://www.amazon.com/OSOYOO-ATmega32U4-arduino-Leonardo-ATmega328/dp/B012FOV17O/[Arduino Leonardo or equivalent].

https://www.arduino.cc/en/Guide/HomePage[Here is a useful resource for uploading the code into an arduino.]

== 3: Prepare the CloudReady Machine
Install CloudReady using the instructions in our https://guide.neverware.com[Guide] until the machine automatically shuts down, right after installation. 

When you turn on the device manually, you will be greeted with the "Welcome!" page. 
*Don't click or type anything unless you know what you are doing.*

This is a keyboard emulator, so the starting position of the screen selection affects the success of the Centipede script. 

Take note of the starting position of the screen selection post-install. You may have to adjust the `selected_on_boot` setting in the script configuration, if it doesn't match the default.


== 4: Execute the code
Plug in the programmed arduino to the prepared CloudReady machine and let it do its thing!

There are long pauses between some steps. Typing into the keyboard or using the mouse/trackpad during runtime will affect the success of the script.

== Additional Resources and Support
https://labs.amplifiedit.com/centipede/[AmplifiedIT Centipede page]


=== Folder structure
....
 AmplifiedIT-Centipede                              => Arduino sketch folder
  ├── Centipede_for_CloudReady_Enrollment.ino       => main Arduino file
  └── ReadMe.adoc                                   => this file
....

=== License
This project is released under the https://opensource.org/licenses/MIT[MIT License].

=== Contributing
To contribute to this project please open an issue or pull request.

=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]

